version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:8.15.1

    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: '-Xmx3g'

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/repo

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install --ignore-engines

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Test firestore rules
          command: |
            sudo apt-get update
            sudo apt install openjdk-8-jdk
            sudo ./node_modules/.bin/firebase setup:emulators:firestore
            sudo ./node_modules/.bin/firebase emulators:exec --only firestore ./node_modules/.bin/mocha

      - run:
          name: Build and test
          command: |
            ./node_modules/.bin/prettier  --check "src/**/**.js"
            npm run build
            npm run test:ci
