export const ADD_EMAILS = "ADD_EMAILS";
export const ADD_EMAIL_ERROR = "ADD_EMAIL_ERROR";
export const ADD_EMAIL_SUCCESS = "ADD_EMAIL_SUCCESS";

/** Invitation List */
export const CREATE_INVITATION_LIST_SUCCESS = "CREATE_INVITATION_LIST_SUCCESS";
export const CREATE_INVITATION_LIST_ERROR = "CREATE_INVITATION_LIST_ERROR";
export const LOAD_INVITATION_LIST_SUCCESS = "LOAD_INVITATION_LIST_SUCCESS";
export const LOAD_INVITATION_LIST_ERROR = "LOAD_INVITATION_LIST_ERROR";

/** Invitation */
export const CREATE_INVITATION_SUCCESS = "CREATE_INVITATION_SUCCESS";
export const CREATE_INVITATION_ERROR = "CREATE_INVITATION_ERROR";
export const LOAD_INVITATION_SUCCESS = "LOAD_INVITATION_SUCCESS";
export const LOAD_INVITATION_ERROR = "LOAD_INVITATION_ERROR";
export const UPDATE_INVITATION_SUCCESS = "UPDATE_INVITATION_SUCCESS";
export const UPDATE_INVITATION_ERROR = "UPDATE_INVITATION_ERROR";
