export const INIT_AUTH = 'INIT_AUTH';

export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const MAGIC_LINK_SUCCESS = 'MAGIC_LINK_SUCCESS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
